export type ProductStatus = "active" | "draft" | "paused";
export type ProductSource = "manual" | "logzz" | "mercado_livre";

export type Product = {
  id: string;
  slug?: string;
  title: string;
  brand: string;
  category: string;
  subcategory: string;
  price: number;
  oldPrice?: number;
  rating: number;
  reviewCount: number;
  soldCount: number;
  fullShipping: boolean;
  freeShipping: boolean;
  installmentText: string;
  imageUrl: string;
  gallery: string[];
  description: string;
  features: string[];
  tags: string[];
  affiliateUrl: string;
  status: ProductStatus;
  featured?: boolean;
  shortDescription?: string;
  specifications?: Array<{ name: string; value: string }>;
  source?: ProductSource;
  externalOfferName?: string;
  createdAt: string;
};
