import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/admin-authorization";
import { importMercadoLivreProduct,MercadoLivreImportError,type ImportErrorCode } from "@/lib/mercado-livre-importer";
import { getValidMercadoLivreToken,ML_OAUTH_COOKIE,MercadoLivreOAuthError,secureCookieOptions } from "@/lib/mercado-livre-oauth";
export const runtime="nodejs";
const statusByCode:Record<ImportErrorCode,number>={INVALID_URL:400,ITEM_ID_NOT_FOUND:400,USER_PRODUCT_UNSUPPORTED:422,CATALOG_DATA_INCOMPLETE:422,OFFER_ITEM_NOT_FOUND:404,API_NOT_FOUND:404,API_UNAUTHORIZED:401,API_FORBIDDEN:403,TIMEOUT:504,NETWORK_ERROR:502,UNEXPECTED_RESPONSE:502,NORMALIZATION_ERROR:422};
function apiErrorMessage(error:MercadoLivreImportError){const status=Number(error.details?.status),apiCode=String(error.details?.apiCode??"unknown"),apiMessage=String(error.details?.apiMessage??"Sem mensagem retornada pela API.");return`HTTP ${status}\nerror: ${apiCode}\nmessage: ${apiMessage}`}
function logFailure(requestId:string,error:unknown,url:string){const safeInput=(()=>{try{const parsed=new URL(url);return`${parsed.origin}${parsed.pathname}`}catch{return"invalid-url"}})();console.error("[product-import] failed",{requestId,input:safeInput,code:error instanceof MercadoLivreImportError||error instanceof MercadoLivreOAuthError?error.code:"INTERNAL_ERROR",message:error instanceof Error?error.message:String(error),details:error instanceof MercadoLivreImportError||error instanceof MercadoLivreOAuthError?error.details:undefined,stack:error instanceof Error?error.stack:undefined});}
function rotateToken(response:NextResponse,refreshedCookie?:string){if(refreshedCookie)response.cookies.set(ML_OAUTH_COOKIE,refreshedCookie,secureCookieOptions());return response}
export async function POST(request:Request){const requestId=crypto.randomUUID(),admin=await requireAdmin();if(!admin.ok)return NextResponse.json({error:admin.error,code:admin.status===401?"SESSION_EXPIRED":"FORBIDDEN",requestId},{status:admin.status});let url="";try{const body=await request.json() as{url?:unknown};url=typeof body.url==="string"?body.url.trim():""}catch{return NextResponse.json({error:"Requisição inválida.",code:"INVALID_REQUEST",requestId},{status:400})}if(!url||url.length>2048)return NextResponse.json({error:"URL inválida. Informe o endereço completo do anúncio.",code:"INVALID_URL",requestId},{status:400});let refreshedCookie:string|undefined;try{const oauth=await getValidMercadoLivreToken();refreshedCookie=oauth.refreshedCookie;const product=await importMercadoLivreProduct(url,oauth.accessToken);console.info("[product-import] succeeded",{requestId,sourceId:product.sourceId});return rotateToken(NextResponse.json({product,requestId}),refreshedCookie)}catch(error){logFailure(requestId,error,url);if(error instanceof MercadoLivreOAuthError)return NextResponse.json({error:error.message,code:error.code,requestId,authorizeUrl:"/api/auth/mercado-livre/start"},{status:error.status});if(error instanceof MercadoLivreImportError){if(error.details?.apiResponse===true){const status=Number(error.details.status);return rotateToken(NextResponse.json({error:apiErrorMessage(error)},{status:Number.isInteger(status)&&status>=400&&status<=599?status:502}),refreshedCookie)}return rotateToken(NextResponse.json({error:error.message,code:error.code,requestId},{status:statusByCode[error.code]}),refreshedCookie)}return rotateToken(NextResponse.json({error:"Falha interna ao importar produto. Informe o código de diagnóstico ao suporte.",code:"INTERNAL_ERROR",requestId},{status:500}),refreshedCookie)}}
