"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useMemo, useState } from "react";
import type { DiscoveryCandidate } from "@/lib/product-discovery";
import { candidateSelectable } from "@/lib/product-discovery";

type Summary={selected:number;created:number;duplicates:number;failed:number;reviewRequired:number;results:Array<{externalOfferId:string;status:string;message:string}>};
export default function DiscoveryClient(){
  const[categories,setCategories]=useState<string[]>([]),[category,setCategory]=useState(""),[keywords,setKeywords]=useState("");
  const[quantity,setQuantity]=useState<5|10|20>(10),[minPrice,setMinPrice]=useState(""),[maxPrice,setMaxPrice]=useState(""),[minDiscount,setMinDiscount]=useState("");
  const[items,setItems]=useState<DiscoveryCandidate[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[loading,setLoading]=useState(false);
  const[importing,setImporting]=useState(false),[message,setMessage]=useState(""),[limitation,setLimitation]=useState(""),[summary,setSummary]=useState<Summary|null>(null);
  const[order,setOrder]=useState("score");
  useEffect(()=>{fetch("/api/admin/categories").then(r=>r.json()).then(body=>{const names=(body.categories??[]).filter((item:{status:string})=>item.status==="active").map((item:{name:string})=>item.name);setCategories(names);setCategory(names[0]??"")}).catch(()=>setMessage("Não foi possível carregar as categorias."))},[]);
  const sorted=useMemo(()=>[...items].sort((a,b)=>order==="price"?a.price-b.price:order==="discount"?b.discountPercent-a.discountPercent:order==="specs"?b.specificationCount-a.specificationCount:b.score-a.score),[items,order]);
  async function search(){setLoading(true);setMessage("");setSummary(null);setSelected(new Set());try{const response=await fetch("/api/admin/discovery/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category,keywords,quantity,minPrice:Number(minPrice)||undefined,maxPrice:Number(maxPrice)||undefined,minDiscount:Number(minDiscount)||undefined})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Busca indisponível.");setItems(body.candidates??[]);setLimitation(body.limitation??"");if(!body.candidates?.length)setMessage("Nenhuma oportunidade compatível foi encontrada nos anúncios da conta conectada.")}catch(error){setItems([]);setMessage(error instanceof Error?error.message:"Busca indisponível.")}finally{setLoading(false)}}
  function toggle(item:DiscoveryCandidate){if(!candidateSelectable(item))return;setSelected(current=>{const next=new Set(current);if(next.has(item.externalOfferId))next.delete(item.externalOfferId);else if(next.size<20)next.add(item.externalOfferId);return next})}
  function selectAll(){setSelected(new Set(sorted.filter(candidateSelectable).slice(0,20).map(item=>item.externalOfferId)))}
  async function importSelected(){setImporting(true);setMessage("");try{const response=await fetch("/api/admin/discovery/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({candidates:[...selected].map(externalOfferId=>({externalOfferId})),category,confirmDraft:true})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Importação indisponível.");setSummary(body.summary);setMessage(`${body.summary.created} rascunhos criados. Nenhum produto foi publicado automaticamente.`)}catch(error){setMessage(error instanceof Error?error.message:"Importação indisponível.")}finally{setImporting(false)}}
  const summaryText=summary?`Discovery Ativa Hub\nSelecionados: ${summary.selected}\nRascunhos: ${summary.created}\nDuplicados: ${summary.duplicates}\nFalhas: ${summary.failed}\nRevisão manual: ${summary.reviewRequired}\n${summary.results.map(item=>`${item.externalOfferId}: ${item.message}`).join("\n")}`:"";
  return <main className="mx-auto max-w-7xl p-4 sm:p-6"><p className="text-sm font-bold uppercase tracking-wider text-amber-600">Catálogo</p><h1 className="mt-1 text-3xl font-black">Discovery</h1><p className="mt-2 text-slate-600">Descubra oportunidades entre os anúncios da conta Mercado Livre conectada. Os itens são sempre salvos como rascunho.</p>
    <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">Categoria<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3">{categories.map(item=><option key={item}>{item}</option>)}</select></label><label className="text-sm font-bold md:col-span-2">Palavras-chave<input value={keywords} onChange={e=>setKeywords(e.target.value)} maxLength={100} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label className="text-sm font-bold">Quantidade<select value={quantity} onChange={e=>setQuantity(Number(e.target.value) as 5|10|20)} className="mt-1 min-h-11 w-full rounded-xl border px-3"><option>5</option><option>10</option><option>20</option></select></label>{[["Preço mínimo",minPrice,setMinPrice],["Preço máximo",maxPrice,setMaxPrice],["Desconto mínimo (%)",minDiscount,setMinDiscount]].map(([label,value,setter])=><label key={label as string} className="text-sm font-bold">{label as string}<input type="number" min="0" value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>)}</div><button onClick={search} disabled={loading||!category} className="mt-5 min-h-11 rounded-xl bg-slate-900 px-5 font-bold text-white disabled:opacity-50">{loading?"Buscando oportunidades…":"Buscar oportunidades"}</button></section>
    {limitation?<p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">{limitation}</p>:null}{message?<p role="status" className="mt-4 rounded-xl border bg-white p-4 font-bold">{message}</p>:null}
    {items.length?<section className="mt-6"><div className="flex flex-wrap items-center gap-3"><b>{selected.size} de 20 selecionados</b><button onClick={selectAll} className="text-sm font-bold underline">Selecionar todos</button><button onClick={()=>setSelected(new Set())} className="text-sm font-bold underline">Limpar seleção</button><select value={order} onChange={e=>setOrder(e.target.value)} className="ml-auto min-h-10 rounded-xl border px-3 text-sm"><option value="score">Maior pontuação</option><option value="price">Menor preço</option><option value="discount">Maior desconto</option><option value="specs">Mais especificações</option></select></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{sorted.map(item=>{const selectable=candidateSelectable(item);return <article key={item.externalOfferId} className={`rounded-2xl border bg-white p-4 shadow-sm ${!selectable?"opacity-70":""}`}><div className="flex gap-4"><input type="checkbox" checked={selected.has(item.externalOfferId)} disabled={!selectable} onChange={()=>toggle(item)} aria-label={`Selecionar ${item.title}`}/><img src={item.imageUrl} alt="" className="size-28 rounded-xl object-contain"/><div className="min-w-0"><h2 className="font-black">{item.title}</h2><p className="mt-2 text-xl font-black">R$ {item.price.toFixed(2)}</p>{item.oldPrice?<p className="text-sm text-slate-500 line-through">R$ {item.oldPrice.toFixed(2)}</p>:null}{item.discountPercent>0?<span className="text-sm font-bold text-green-700">{item.discountPercent}% verificável</span>:null}<p className="mt-2 text-sm">{item.suggestedCategory}</p></div></div><div className="mt-4 flex items-center justify-between"><b>Pontuação Ativa Hub: {item.score}/100</b>{item.duplicate?<span className="rounded-full bg-slate-200 px-2 py-1 text-xs font-bold">Já cadastrado</span>:null}</div><ul className="mt-3 text-sm text-green-800">{item.reasons.map(reason=><li key={reason}>✓ {reason}</li>)}</ul><ul className="mt-2 text-sm text-amber-800">{item.warnings.map(warning=><li key={warning}>⚠ {warning}</li>)}</ul><a href={item.offerUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex font-bold underline">Ver oferta</a></article>})}</div><button onClick={importSelected} disabled={!selected.size||importing} className="mt-5 min-h-12 rounded-xl bg-amber-400 px-6 font-black disabled:opacity-50">{importing?"Validando, importando e gerando…":"Importar selecionados"}</button></section>:null}
    {summary?<section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Resumo da operação</h2><pre className="mt-3 whitespace-pre-wrap text-sm">{summaryText}</pre><button onClick={()=>navigator.clipboard.writeText(summaryText)} className="mt-3 rounded-xl border px-4 py-2 font-bold">Copiar resumo</button></section>:null}
  </main>
}
