import "server-only";
import type { ImportedProduct } from "@/types/product-import";

const API_ORIGIN = "https://api.mercadolibre.com";
const DIRECT_HOSTS = new Set(["mercadolivre.com.br", "www.mercadolivre.com.br", "produto.mercadolivre.com.br"]);
const SHORT_HOSTS = new Set(["meli.la"]);
const TIMEOUT_MS = 10_000;

export type ImportErrorCode = "INVALID_URL" | "ITEM_ID_NOT_FOUND" | "API_NOT_FOUND" | "API_FORBIDDEN" | "TIMEOUT" | "NETWORK_ERROR" | "UNEXPECTED_RESPONSE" | "NORMALIZATION_ERROR";

export class MercadoLivreImportError extends Error {
  constructor(public readonly code: ImportErrorCode, message: string, public readonly details?: Record<string, unknown>, public readonly cause?: unknown) {
    super(message); this.name = "MercadoLivreImportError";
  }
}

type MlItem = { id?:unknown; title?:unknown; price?:unknown; original_price?:unknown; permalink?:unknown; thumbnail?:unknown; pictures?:unknown; attributes?:unknown; category_id?:unknown };
type MetadataDraft = { title?:string; description?:string; price?:number; oldPrice?:number; images:string[]; brand?:string; category?:string; specifications:Array<{name:string;value:string}>; canonicalUrl?:string };

function safeUrl(rawUrl:string):URL {
  let url:URL;
  try { url = new URL(rawUrl); } catch { throw new MercadoLivreImportError("INVALID_URL", "URL inválida. Informe o endereço completo do anúncio."); }
  const host=url.hostname.toLowerCase();
  if(url.protocol!=="https:"||(!DIRECT_HOSTS.has(host)&&!SHORT_HOSTS.has(host))) throw new MercadoLivreImportError("INVALID_URL", "URL inválida. Use um link HTTPS do Mercado Livre Brasil.", {host,protocol:url.protocol});
  return url;
}

function itemIdFromUrl(url:URL):string|null { const match=`${url.pathname}${url.search}`.match(/\bMLB[-_]?([0-9]{6,})\b/i); return match?`MLB${match[1]}`:null; }
export function getMercadoLivreItemId(rawUrl:string):string { const id=itemIdFromUrl(safeUrl(rawUrl)); if(!id)throw new MercadoLivreImportError("ITEM_ID_NOT_FOUND", "Código MLB não encontrado na URL do anúncio."); return id; }

function abortError(error:unknown){return error instanceof Error&&(error.name==="AbortError"||error.name==="TimeoutError"||/timeout/i.test(error.message));}
async function request(url:string,accept:string,authorization?:string):Promise<Response>{try{return await fetch(url,{headers:{Accept:accept,"User-Agent":"AtivaHub/2.0 (+product-importer)",...(authorization?{Authorization:`Bearer ${authorization}`}:{})},redirect:"manual",cache:"no-store",signal:AbortSignal.timeout(TIMEOUT_MS)})}catch(error){if(abortError(error))throw new MercadoLivreImportError("TIMEOUT","A consulta ao Mercado Livre excedeu 10 segundos.",{url},error);throw new MercadoLivreImportError("NETWORK_ERROR","Erro de rede ao consultar o Mercado Livre.",{url},error)}}

async function apiJson<T>(path:string,accessToken:string,optional=false):Promise<T|undefined>{const url=`${API_ORIGIN}${path}`;const response=await request(url,"application/json",accessToken);if(response.status===404){if(optional)return undefined;throw new MercadoLivreImportError("API_NOT_FOUND","O anúncio não foi encontrado na API do Mercado Livre (404).",{url,status:404})}if(response.status===403)throw new MercadoLivreImportError("API_FORBIDDEN","A API do Mercado Livre recusou a consulta (403). Configure um token oficial ou use o fallback de metadados públicos.",{url,status:403,hasToken:Boolean(accessToken)});if(!response.ok)throw new MercadoLivreImportError("UNEXPECTED_RESPONSE",`A API do Mercado Livre respondeu com status inesperado (${response.status}).`,{url,status:response.status,contentType:response.headers.get("content-type")});const contentType=response.headers.get("content-type")??"";if(!contentType.includes("json"))throw new MercadoLivreImportError("UNEXPECTED_RESPONSE","A API do Mercado Livre retornou um formato inesperado.",{url,status:response.status,contentType});try{return await response.json() as T}catch(error){throw new MercadoLivreImportError("UNEXPECTED_RESPONSE","A API do Mercado Livre retornou JSON inválido.",{url,status:response.status},error)}}

function decodeHtml(value:string){return value.replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n)));}
function meta(html:string,key:string){const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const patterns=[new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']*)["'][^>]*>`,"i"),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${escaped}["'][^>]*>`,"i")];for(const pattern of patterns){const match=html.match(pattern);if(match)return decodeHtml(match[1].trim())}return undefined;}
function jsonLdProducts(html:string):Record<string,unknown>[] {const found:Record<string,unknown>[]=[];for(const match of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const parsed=JSON.parse(decodeHtml(match[1]));const queue=Array.isArray(parsed)?parsed:[parsed];for(const node of queue){if(node&&typeof node==="object"&&Array.isArray(node["@graph"]))queue.push(...node["@graph"]);if(node&&typeof node==="object"&&String(node["@type"]).toLowerCase()==="product")found.push(node)}}catch{/* Outros scripts JSON-LD inválidos não impedem o fallback. */}}return found;}
function strings(value:unknown):string[]{if(typeof value==="string")return[value];if(Array.isArray(value))return value.flatMap(strings);if(value&&typeof value==="object"&&"url" in value)return strings((value as{url:unknown}).url);return[];}
function numberValue(value:unknown):number|undefined{if(typeof value==="number")return Number.isFinite(value)&&value>0?value:undefined;let text=String(value??"").replace(/[^0-9,.-]/g,"");if(text.includes(",")&&text.includes("."))text=text.lastIndexOf(",")>text.lastIndexOf(".")?text.replace(/\./g,"").replace(",","."):text.replace(/,/g,"");else if(text.includes(","))text=text.replace(",",".");const number=Number(text);return Number.isFinite(number)&&number>0?number:undefined;}
function metadataFromHtml(html:string,finalUrl:string):MetadataDraft {if(/account-verification|suspicious-traffic/i.test(`${finalUrl} ${html.slice(0,3000)}`))throw new MercadoLivreImportError("API_FORBIDDEN","O Mercado Livre bloqueou o acesso aos metadados públicos (403/verificação de tráfego). Não houve tentativa de contornar o bloqueio.",{finalUrl});const product=jsonLdProducts(html)[0];const offers=product?.offers&&typeof product.offers==="object"?(Array.isArray(product.offers)?product.offers[0]:product.offers) as Record<string,unknown>:undefined;const properties=Array.isArray(product?.additionalProperty)?product.additionalProperty as Record<string,unknown>[]:[];const specifications=properties.map(p=>({name:String(p.name??"").trim(),value:String(p.value??"").trim()})).filter(p=>p.name&&p.value);const images=[...strings(product?.image),meta(html,"og:image"),meta(html,"twitter:image")].filter((v):v is string=>Boolean(v?.startsWith("https://")));const canonical=html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i)?.[1];return{title:String(product?.name??meta(html,"og:title")??"").trim(),description:String(product?.description??meta(html,"og:description")??"").trim(),price:numberValue(offers?.price??meta(html,"product:price:amount")),images:[...new Set(images)],brand:typeof product?.brand==="object"?String((product.brand as Record<string,unknown>).name??""):String(product?.brand??""),category:String(product?.category??""),specifications,canonicalUrl:canonical?.startsWith("https://")?decodeHtml(canonical):finalUrl};}

async function publicMetadata(startUrl:URL):Promise<{draft:MetadataDraft;itemId:string|null}>{let current=startUrl;for(let redirects=0;redirects<=3;redirects++){const response=await request(current.toString(),"text/html,application/xhtml+xml");if([301,302,303,307,308].includes(response.status)){const location=response.headers.get("location");if(!location)throw new MercadoLivreImportError("UNEXPECTED_RESPONSE","O redirecionamento do anúncio não informou o destino.",{status:response.status});current=new URL(location,current);if(!DIRECT_HOSTS.has(current.hostname.toLowerCase()))throw new MercadoLivreImportError("INVALID_URL","O link redirecionou para um domínio não autorizado.",{host:current.hostname});continue}if(response.status===404)throw new MercadoLivreImportError("API_NOT_FOUND","A página pública do anúncio não foi encontrada (404).",{url:current.toString()});if(response.status===403)throw new MercadoLivreImportError("API_FORBIDDEN","O Mercado Livre recusou o acesso aos metadados públicos (403).",{url:current.toString()});if(!response.ok)throw new MercadoLivreImportError("UNEXPECTED_RESPONSE",`A página do anúncio respondeu com status inesperado (${response.status}).`,{url:current.toString(),status:response.status});const type=response.headers.get("content-type")??"";if(!type.includes("html"))throw new MercadoLivreImportError("UNEXPECTED_RESPONSE","A página do anúncio retornou um formato inesperado.",{contentType:type});const html=await response.text();return{draft:metadataFromHtml(html,current.toString()),itemId:itemIdFromUrl(current)}}throw new MercadoLivreImportError("UNEXPECTED_RESPONSE","O link do anúncio excedeu o limite seguro de redirecionamentos.");}

function normalizeApi(item:MlItem,description?:{plain_text?:unknown},category?:{name?:unknown}):ImportedProduct {try{const attributes=Array.isArray(item.attributes)?item.attributes as Array<Record<string,unknown>>:[];const specifications=attributes.map(a=>({name:String(a.name??"").trim(),value:String(a.value_name??"").trim()})).filter(a=>a.name&&a.value);const pictures=Array.isArray(item.pictures)?item.pictures as Array<Record<string,unknown>>:[];const images=pictures.flatMap(p=>strings(p.secure_url??p.url)).filter(url=>url.startsWith("https://"));const thumbnail=String(item.thumbnail??"").replace(/^http:/,"https:");if(!images.length&&thumbnail.startsWith("https://"))images.push(thumbnail);const title=String(item.title??"").trim(),price=numberValue(item.price),id=String(item.id??"").trim();if(!id||!title||!price||!images.length)throw new Error("Campos obrigatórios ausentes: id, title, price ou pictures.");const text=String(description?.plain_text??"").trim();const oldPrice=numberValue(item.original_price);return{source:"Mercado Livre",sourceId:id,sourceUrl:String(item.permalink??"")||`https://produto.mercadolivre.com.br/${id}`,title,brand:specifications.find(a=>/^(marca|brand)$/i.test(a.name))?.value??"",category:String(category?.name??""),shortDescription:text.slice(0,240),description:text,price,oldPrice:oldPrice&&oldPrice>=price?oldPrice:null,images:[...new Set(images)],specifications}}catch(error){throw new MercadoLivreImportError("NORMALIZATION_ERROR","Falha ao normalizar os dados retornados pela API do Mercado Livre.",{source:"api"},error)}}
function normalizeMetadata(draft:MetadataDraft,itemId:string,url:string):ImportedProduct {try{if(!draft.title||!draft.price||!draft.images.length)throw new Error("Metadados obrigatórios ausentes: título, preço ou imagem.");const description=draft.description??"";return{source:"Mercado Livre",sourceId:itemId,sourceUrl:draft.canonicalUrl??url,title:draft.title,brand:draft.brand??"",category:draft.category??"",shortDescription:description.slice(0,240),description,price:draft.price,oldPrice:draft.oldPrice??null,images:draft.images,specifications:draft.specifications}}catch(error){throw new MercadoLivreImportError("NORMALIZATION_ERROR","Os metadados públicos não contêm título, preço e imagem suficientes para importar o produto.",{source:"metadata"},error)}}

export async function importMercadoLivreProduct(rawUrl:string,accessToken:string):Promise<ImportedProduct>{const original=safeUrl(rawUrl);let itemId=itemIdFromUrl(original);let prefetched:{draft:MetadataDraft;itemId:string|null}|undefined;if(!itemId){prefetched=await publicMetadata(original);itemId=prefetched.itemId;if(!itemId)throw new MercadoLivreImportError("ITEM_ID_NOT_FOUND","Código MLB não encontrado na URL nem nos metadados do anúncio.");}try{const item=await apiJson<MlItem>(`/items/${encodeURIComponent(itemId)}`,accessToken);const [description,category]=await Promise.all([apiJson<{plain_text?:unknown}>(`/items/${encodeURIComponent(itemId)}/description`,accessToken,true),item?.category_id?apiJson<{name?:unknown}>(`/categories/${encodeURIComponent(String(item.category_id))}`,accessToken,true):undefined]);return normalizeApi(item!,description,category)}catch(error){if(!(error instanceof MercadoLivreImportError)||!(["API_FORBIDDEN","NETWORK_ERROR","TIMEOUT","UNEXPECTED_RESPONSE"] as ImportErrorCode[]).includes(error.code))throw error;try{const metadata=prefetched??await publicMetadata(original);return normalizeMetadata(metadata.draft,itemId,original.toString())}catch(fallbackError){throw new MercadoLivreImportError(fallbackError instanceof MercadoLivreImportError?fallbackError.code:"UNEXPECTED_RESPONSE",fallbackError instanceof MercadoLivreImportError?fallbackError.message:"Falha ao consultar os metadados públicos do anúncio.",{apiFailure:{code:error.code,details:error.details},fallbackFailure:fallbackError instanceof MercadoLivreImportError?{code:fallbackError.code,details:fallbackError.details}:undefined},fallbackError)}}}
