import "server-only";
import { createCipheriv, createDecipheriv, createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { cookies } from "next/headers";

export const ML_OAUTH_COOKIE="ativa_ml_oauth";
export const ML_STATE_COOKIE="ativa_ml_oauth_state";
export const ML_REDIRECT_URI=process.env.MERCADO_LIVRE_REDIRECT_URI?.trim()||"https://ativa-hub.vercel.app/api/auth/mercado-livre/callback";
const TOKEN_URL="https://api.mercadolibre.com/oauth/token";
const COOKIE_MAX_AGE=60*60*24*180;

type OAuthToken={accessToken:string;refreshToken:string;expiresAt:number;userId:string;scope:string};
export type ValidOAuthToken={accessToken:string;refreshedCookie?:string};
type OAuthResponse={access_token?:unknown;refresh_token?:unknown;expires_in?:unknown;user_id?:unknown;scope?:unknown;error?:unknown;error_description?:unknown};

export class MercadoLivreOAuthError extends Error{constructor(public readonly code:"OAUTH_CONFIG"|"OAUTH_REQUIRED"|"OAUTH_STATE"|"OAUTH_EXCHANGE"|"OAUTH_REFRESH",message:string,public readonly status=401,public readonly details?:Record<string,unknown>){super(message);this.name="MercadoLivreOAuthError"}}
function credentials(){const clientId=process.env.MERCADO_LIVRE_CLIENT_ID?.trim(),clientSecret=process.env.MERCADO_LIVRE_CLIENT_SECRET?.trim();if(!clientId||!clientSecret)throw new MercadoLivreOAuthError("OAUTH_CONFIG","Credenciais OAuth do Mercado Livre não configuradas.",503);return{clientId,clientSecret}}
function key(){return createHash("sha256").update(credentials().clientSecret).update("ativa-hub:mercado-livre-oauth:v1").digest()}
function base64url(value:Buffer){return value.toString("base64url")}
export function sealOAuthData(value:unknown){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key(),iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(value),"utf8"),cipher.final()]);return [base64url(iv),base64url(cipher.getAuthTag()),base64url(encrypted)].join(".")}
export function openOAuthData<T>(sealed:string):T{try{const[iv,tag,data]=sealed.split(".").map(value=>Buffer.from(value,"base64url"));if(!iv||!tag||!data)throw new Error("Invalid envelope");const decipher=createDecipheriv("aes-256-gcm",key(),iv);decipher.setAuthTag(tag);return JSON.parse(Buffer.concat([decipher.update(data),decipher.final()]).toString("utf8")) as T}catch{throw new MercadoLivreOAuthError("OAUTH_REQUIRED","A autorização do Mercado Livre está ausente ou inválida.",401)}}
export function secureCookieOptions(maxAge=COOKIE_MAX_AGE){return{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax" as const,path:"/",maxAge}}
export function createAuthorizationRequest(){const{clientId}=credentials(),state=base64url(randomBytes(32)),verifier=base64url(randomBytes(48)),challenge=base64url(createHash("sha256").update(verifier).digest());const authorize=new URL("https://auth.mercadolivre.com.br/authorization");authorize.searchParams.set("response_type","code");authorize.searchParams.set("client_id",clientId);authorize.searchParams.set("redirect_uri",ML_REDIRECT_URI);authorize.searchParams.set("state",state);authorize.searchParams.set("code_challenge",challenge);authorize.searchParams.set("code_challenge_method","S256");authorize.searchParams.set("scope","offline_access read");return{url:authorize,stateCookie:sealOAuthData({state,verifier,issuedAt:Date.now()})}}
export function validateOAuthState(sealed:string|undefined,received:string|undefined){if(!sealed||!received)throw new MercadoLivreOAuthError("OAUTH_STATE","Não foi possível validar o state da autorização.",400);const data=openOAuthData<{state?:string;verifier?:string;issuedAt?:number}>(sealed);if(!data.state||!data.verifier||!data.issuedAt||Date.now()-data.issuedAt>10*60*1000)throw new MercadoLivreOAuthError("OAUTH_STATE","A autorização expirou. Inicie a conexão novamente.",400);const expected=Buffer.from(data.state),actual=Buffer.from(received);if(expected.length!==actual.length||!timingSafeEqual(expected,actual))throw new MercadoLivreOAuthError("OAUTH_STATE","O state da autorização é inválido.",400);return data.verifier}
async function tokenRequest(parameters:Record<string,string>,operation:"exchange"|"refresh"):Promise<OAuthToken>{const{clientId,clientSecret}=credentials();let response:Response;try{response=await fetch(TOKEN_URL,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({...parameters,client_id:clientId,client_secret:clientSecret}),cache:"no-store",signal:AbortSignal.timeout(10_000)})}catch(error){throw new MercadoLivreOAuthError(operation==="exchange"?"OAUTH_EXCHANGE":"OAUTH_REFRESH",operation==="exchange"?"Erro de rede ao concluir a autorização do Mercado Livre.":"Erro de rede ao renovar a autorização do Mercado Livre.",502,{cause:error instanceof Error?error.name:"unknown"})}let body:OAuthResponse={};try{body=await response.json() as OAuthResponse}catch{/* O status é suficiente; o corpo bruto nunca é registrado. */}if(!response.ok)throw new MercadoLivreOAuthError(operation==="exchange"?"OAUTH_EXCHANGE":"OAUTH_REFRESH",operation==="exchange"?"O Mercado Livre recusou a troca do código de autorização.":"A autorização do Mercado Livre expirou ou foi revogada. Conecte novamente.",response.status,{status:response.status,oauthError:String(body.error??"unknown")});const accessToken=String(body.access_token??""),refreshToken=String(body.refresh_token??""),expiresIn=Number(body.expires_in);if(!accessToken||!refreshToken||!Number.isFinite(expiresIn)||expiresIn<=0)throw new MercadoLivreOAuthError(operation==="exchange"?"OAUTH_EXCHANGE":"OAUTH_REFRESH","O Mercado Livre retornou uma resposta OAuth inesperada.",502,{status:response.status});return{accessToken,refreshToken,expiresAt:Date.now()+expiresIn*1000,userId:String(body.user_id??""),scope:String(body.scope??"")}}
export async function exchangeAuthorizationCode(code:string,verifier:string){const token=await tokenRequest({grant_type:"authorization_code",code,redirect_uri:ML_REDIRECT_URI,code_verifier:verifier},"exchange");return sealOAuthData(token)}
export async function getValidMercadoLivreToken():Promise<ValidOAuthToken>{const store=await cookies(),sealed=store.get(ML_OAUTH_COOKIE)?.value;if(!sealed)throw new MercadoLivreOAuthError("OAUTH_REQUIRED","Conecte uma conta do Mercado Livre para importar produtos.",401);const token=openOAuthData<OAuthToken>(sealed);if(!token.accessToken||!token.refreshToken||!token.expiresAt)throw new MercadoLivreOAuthError("OAUTH_REQUIRED","A autorização do Mercado Livre é inválida. Conecte novamente.",401);if(token.expiresAt-Date.now()>5*60*1000)return{accessToken:token.accessToken};const refreshed=await tokenRequest({grant_type:"refresh_token",refresh_token:token.refreshToken},"refresh");return{accessToken:refreshed.accessToken,refreshedCookie:sealOAuthData(refreshed)}}
