"use client";
import { useEffect, useRef, useState } from "react";
import { Expand, X } from "lucide-react";
import ProductImage from "./ProductImage";
const isValid = (url: string) => url.startsWith("/") || /^https?:\/\//i.test(url);
export default function ProductGallery({ title, imageUrl, gallery = [] }: { title: string; imageUrl?: string; gallery?: string[] }) {
  const images = Array.from(new Set([imageUrl, ...gallery].filter((url): url is string => Boolean(url && isValid(url)))));
  const available = images.length ? images : [""];
  const [selected, setSelected] = useState(0); const [open, setOpen] = useState(false); const closeButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (!open) return; const previous = document.activeElement as HTMLElement | null; const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("keydown", onKeyDown); document.body.style.overflow = "hidden"; closeButton.current?.focus(); return () => { document.removeEventListener("keydown", onKeyDown); document.body.style.overflow = ""; previous?.focus(); }; }, [open]);
  const current = available[Math.min(selected, available.length - 1)];
  return <section aria-label={`Galeria de imagens de ${title}`}><button type="button" onClick={() => setOpen(true)} className="group relative block aspect-square w-full overflow-hidden rounded-2xl border border-slate-200 bg-white focus:outline-none focus-visible:ring-4 focus-visible:ring-amber-300" aria-label={`Ampliar imagem de ${title}`}><ProductImage src={current} alt={title} fill priority sizes="(max-width: 768px) 100vw, 50vw" className="object-contain p-5 transition-transform duration-300 group-hover:scale-105"/><span className="absolute bottom-3 right-3 inline-flex items-center gap-2 rounded-full bg-slate-950/80 px-3 py-2 text-xs font-bold text-white"><Expand size={16} aria-hidden="true"/> Ampliar</span></button>
  {available.length > 1 && <div className="mt-4 flex gap-3 overflow-x-auto pb-2" role="list" aria-label="Miniaturas do produto">{available.map((image, index) => <button key={`${image}-${index}`} type="button" role="listitem" onClick={() => setSelected(index)} aria-label={`Exibir imagem ${index + 1} de ${available.length}`} aria-current={selected === index ? "true" : undefined} className={`relative size-20 shrink-0 overflow-hidden rounded-xl border-2 bg-white focus:outline-none focus-visible:ring-4 focus-visible:ring-amber-300 ${selected === index ? "border-amber-500" : "border-slate-200"}`}><ProductImage src={image} alt="" fill sizes="80px" className="object-contain p-1"/></button>)}</div>}
  {open && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/90 p-4" role="dialog" aria-modal="true" aria-label={`Imagem ampliada de ${title}`} onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><button ref={closeButton} type="button" onClick={() => setOpen(false)} className="absolute right-4 top-4 z-10 inline-flex min-h-11 items-center gap-2 rounded-full bg-white px-4 font-bold text-slate-900 focus:outline-none focus-visible:ring-4 focus-visible:ring-amber-300" aria-label="Fechar imagem ampliada"><X size={20} aria-hidden="true"/> Fechar</button><div className="relative h-[85vh] w-full max-w-6xl"><ProductImage src={current} alt={title} fill sizes="100vw" className="object-contain"/></div></div>}</section>;
}
