"use client";
import { Check, Copy, Facebook, Heart, Share2 } from "lucide-react";
import { useEffect, useState } from "react";
const favoritesKey = "ativa-hub-favorites";
export default function ProductActions({ id, title }: { id: string; title: string }) {
  const [favorite, setFavorite] = useState(false); const [ready, setReady] = useState(false); const [copied, setCopied] = useState(false);
  useEffect(() => { try { setFavorite(JSON.parse(localStorage.getItem(favoritesKey) ?? "[]").includes(id)); } catch { localStorage.removeItem(favoritesKey); } setReady(true); }, [id]);
  function toggleFavorite() { const next = !favorite; setFavorite(next); try { const current: string[] = JSON.parse(localStorage.getItem(favoritesKey) ?? "[]"); localStorage.setItem(favoritesKey, JSON.stringify(next ? Array.from(new Set([...current, id])) : current.filter((item) => item !== id))); } catch { localStorage.setItem(favoritesKey, JSON.stringify(next ? [id] : [])); } }
  async function copyLink() { const url = window.location.href; try { await navigator.clipboard.writeText(url); } catch { const input = document.createElement("textarea"); input.value = url; document.body.appendChild(input); input.select(); document.execCommand("copy"); input.remove(); } setCopied(true); window.setTimeout(() => setCopied(false), 2500); }
  async function nativeShare() { if (navigator.share) { try { await navigator.share({ title, url: window.location.href }); } catch {} } else await copyLink(); }
  const currentUrl = () => encodeURIComponent(window.location.href); const openShare = (base: string) => window.open(`${base}${currentUrl()}`, "_blank", "noopener,noreferrer");
  const button = "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-3 text-sm font-bold text-slate-700 hover:border-slate-400 focus:outline-none focus-visible:ring-4 focus-visible:ring-amber-300";
  return <div className="mt-6 border-t border-slate-200 pt-5"><div className="flex flex-wrap gap-2"><button type="button" onClick={toggleFavorite} disabled={!ready} aria-pressed={favorite} aria-label={favorite ? "Remover dos favoritos" : "Adicionar aos favoritos"} className={`${button} ${favorite ? "border-red-300 bg-red-50 text-red-700" : ""}`}><Heart size={18} fill={favorite ? "currentColor" : "none"} aria-hidden="true"/>{favorite ? "Favoritado" : "Favoritar"}</button><button type="button" onClick={nativeShare} className={button}><Share2 size={18} aria-hidden="true"/> Compartilhar</button><button type="button" onClick={() => openShare("https://wa.me/?text=")} className={button} aria-label="Compartilhar no WhatsApp">WhatsApp</button><button type="button" onClick={() => openShare("https://www.facebook.com/sharer/sharer.php?u=")} className={button} aria-label="Compartilhar no Facebook"><Facebook size={18} aria-hidden="true"/> Facebook</button><button type="button" onClick={() => openShare(`https://twitter.com/intent/tweet?text=${encodeURIComponent(title)}&url=`)} className={button} aria-label="Compartilhar no X">X</button><button type="button" onClick={copyLink} className={button} aria-live="polite">{copied ? <Check size={18} aria-hidden="true"/> : <Copy size={18} aria-hidden="true"/>}{copied ? "Link copiado" : "Copiar link"}</button></div></div>;
}
