import Link from "next/link";
import { ExternalLink, Pencil, Trash2 } from "lucide-react";
import type { Product, ProductSource } from "@/types/product";
import { money } from "@/lib/data";
import ProductImage from "@/components/product/ProductImage";
import { isFeaturedProduct } from "./product-filters";
import StatusBadge from "./StatusBadge";

const sourceLabel: Record<ProductSource, string> = { manual: "Manual", logzz: "Logzz", mercado_livre: "Mercado Livre" };
function Origin({ product }: { product: Product }) {
  const source = product.source ?? "manual";
  return <div className="mt-1 flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-slate-100 px-2 py-1 font-bold text-slate-600">{sourceLabel[source]}</span>{source==="logzz"&&product.externalOfferName?<span className="text-slate-500">Oferta: {product.externalOfferName}</span>:null}</div>;
}
function Actions({ product,onDelete }:{product:Product;onDelete:(product:Product)=>void}) {
  const checkout=product.source==="logzz"?product.affiliateUrl:"";
  return <div className="flex flex-wrap gap-2">{checkout?<a href={checkout} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-9 items-center gap-1 rounded-lg border px-3 text-xs font-bold"><ExternalLink size={14}/>Ver na loja</a>:<Link href={`/produto/${product.id}`} className="inline-flex min-h-9 items-center gap-1 rounded-lg border px-3 text-xs font-bold"><ExternalLink size={14}/>Ver</Link>}<Link href={`/admin/produtos/${product.id}/editar`} className="inline-flex min-h-9 items-center gap-1 rounded-lg border px-3 text-xs font-bold"><Pencil size={14}/>Editar</Link><button onClick={()=>onDelete(product)} className="inline-flex min-h-9 items-center gap-1 rounded-lg border px-3 text-xs font-bold text-red-600"><Trash2 size={14}/>Excluir</button></div>;
}
export default function ProductsList({products,selected,onToggle,onDelete}:{products:Product[];selected:ReadonlySet<string>;onToggle:(id:string)=>void;onDelete:(product:Product)=>void}) {
 return <><div className="hidden overflow-hidden rounded-2xl border bg-white shadow-sm lg:block"><table className="w-full"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Selecionar</th><th>Produto</th><th>Categoria e marca</th><th>Preço</th><th>Status</th><th>Destaque</th><th>Ações</th></tr></thead><tbody className="divide-y">{products.map(product=><tr key={product.id}><td className="p-4"><input aria-label={`Selecionar ${product.title}`} type="checkbox" checked={selected.has(product.id)} onChange={()=>onToggle(product.id)} className="size-4 accent-amber-500"/></td><td><div className="flex items-center gap-3"><div className="relative size-14 shrink-0 overflow-hidden rounded-xl bg-slate-100"><ProductImage src={product.imageUrl} alt={product.title} fill sizes="56px" className="object-cover"/></div><div><b>{product.title}</b><Origin product={product}/></div></div></td><td>{product.category}<small className="block text-slate-500">{product.brand}</small></td><td><b>{money(product.price)}</b>{product.oldPrice?<del className="block text-xs">{money(product.oldPrice)}</del>:null}</td><td><StatusBadge status={product.status}/></td><td>{isFeaturedProduct(product)?"★ Destaque":"—"}</td><td><Actions product={product} onDelete={onDelete}/></td></tr>)}</tbody></table></div><div className="grid gap-4 lg:hidden">{products.map(product=><article key={product.id} className="rounded-2xl border bg-white p-4 shadow-sm"><label className="mb-3 flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={selected.has(product.id)} onChange={()=>onToggle(product.id)} className="size-4 accent-amber-500"/>Selecionar</label><div className="flex gap-4"><div className="relative size-20 shrink-0 overflow-hidden rounded-xl bg-slate-100"><ProductImage src={product.imageUrl} alt={product.title} fill sizes="80px" className="object-cover"/></div><div><h2 className="font-black">{product.title}</h2><p className="text-sm text-slate-500">{product.category} · {product.brand}</p><Origin product={product}/><div className="mt-2"><StatusBadge status={product.status}/></div></div></div><strong className="my-4 block text-lg">{money(product.price)}</strong><Actions product={product} onDelete={onDelete}/></article>)}</div></>;
}
